### ISSUE TITLE
Error when deleting first attached file

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#128]
Deleting first attached file causes an error that page doesn't exist. Delete other attached files don't cause the same behavior.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/784196/14621625/3a3fedd2-0592-11e6-8a59-a31396d3bc31.gif)

**Comment by hectorcorrea** [comment]
This is being addressed in this PR https://github.com/projecthydra-labs/curation_concerns/pull/732

**Comment by eliotjordan** [comment]
Thanks @hectorcorrea. I'll close this ticket then.
