### ISSUE TITLE
Add an existing vector or raster child work to parent

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#165]
Allow the user to add an existing vector or raster child work to parent rather than just create new a new work. This might also be useful in CurationConcerns.

**Comment by jrgriffiniii** [comment]
Please note that this may be affected by the update of CurationConcerns prior to the release of Sufia 7.1.0 (https://github.com/projecthydra/sufia/releases/tag/v7.1.0)
