### ISSUE TITLE
Use institution name as default for provenance

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#169]
Use institution name as default for dc:provenance. The document builder (geoblacklight specifically) needs a provenance to build a layer slug.  Perhaps  slugs should come from `curation_concerns.institution_name` rather than provenance?

**Comment by drh-stanford** [comment]
Does `curation_concerns.institution_name` exist already, or do we need to create that configuration?

**Comment by eliotjordan** [comment]
https://github.com/projecthydra/curation_concerns/blob/master/config/locales/curation_concerns.en.yml#L4

**Comment by eliotjordan** [comment]
Strange that is set in a locales file rather than in a regular config file. I suppose that `Peking University` in English is `北京大学` in Chinese. Hadn't thought much about multilingual GeoBlacklight.

**Comment by drh-stanford** [comment]
We also need to add a URI prefix for the `dc_identifier_s`

**Comment by drh-stanford** [comment]
```
[2] pry(#<RSpec::ExampleGroups::GeoConcernsDiscoveryDocumentBuilder::VectorWork::Required>)> I18n.t('curation_concerns.institution.name').parameterize
=> "your-institution"
```

we need to add a URI here: https://github.com/projecthydra/curation_concerns/blob/553907a96683d19e3d7702ff1a409b09cc15dd85/config/locales/curation_concerns.en.yml#L18
