### ISSUE TITLE
Improve geo concerns vagrant box

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#172]

**Comment by drh-stanford** [comment]
For geoserver see https://github.com/drh-stanford/geoserver-vagrant

**Comment by eliotjordan** [comment]
https://github.com/geoconcerns/geo-concerns-vagrant

**Comment by eliotjordan** [comment]
If there are no objections, I think we can close this issue.

See:
https://github.com/geoconcerns/geo-concerns-vagrant/pull/3
https://github.com/geoconcerns/geo-concerns-vagrant-base
