### ISSUE TITLE
Create test data

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#25]
Create data for georectified image for testing and demonstration.

- image file and image file metadata
- georectified image file and iso metadata
- feature extraction and iso metadata

**Comment by johnhuck** [comment]
Larry has identified this resource as a good sample for our purposes. You can find the files to download under the "data & analysis." http://dx.doi.org/10.7939/DVN/10200

Larry is working to create basic iso metadata in arcGIS for the georectified file and feature extraction, and I will add them to https://github.com/projecthydra-labs/geo_concerns/tree/master/test-data as they are ready.

I'll create a basic dublin core record for the basic scan so we will have some kind of external metadata to play with for the image.

**Comment by eliotjordan** [comment]
:+1: :tada:

**Comment by johnhuck** [comment]
Uploaded metadata records to test-data folder
