### ISSUE TITLE
Remove image derivative method?

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#265]
Do we need the `image_derivatives` method in `GeoConcerns::FileSet::Derivatives`? Seems redundant and could cause conflicts with overrides in host applications.

https://github.com/projecthydra-labs/geo_concerns/blob/master/app/models/concerns/geo_concerns/file_set/derivatives.rb#L21-L28

**Comment by eliotjordan** [comment]
@drh-stanford Can you think of any reason why we would need to process scanned map / image derivatives in a special way?

**Comment by drh-stanford** [comment]
is that code overriding regular hydra-derivatives? i don't think we need that if so...

**Comment by eliotjordan** [comment]
@drh-stanford Yeah, we're just overriding hydra-derivatives. PR to fix this: https://github.com/projecthydra-labs/geo_concerns/pull/266
