### ISSUE TITLE
Inject file set controller behaviors rather than override file set controller class

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#273]
https://github.com/projecthydra-labs/geo_concerns/blob/master/lib/generators/geo_concerns/install_generator.rb#L47-L50

https://github.com/projecthydra-labs/geo_concerns/blob/master/lib/generators/geo_concerns/templates/controllers/curation_concerns/file_sets_controller.rb#L3-L5

**Comment by afred** [comment]
dupe of #291
