### ISSUE TITLE
Upgrade to curation_concerns 0.3.0

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#29]
Should we upgrade to [version 0.2.0](https://github.com/projecthydra-labs/curation_concerns/releases)? It is currently tagged as 'pre-release'.  Or, should we wait?

**Comment by jrgriffiniii** [comment]
Reviewing this issue, I believe that it was decided that we are to update to0.3.0.  Please correct me if I am mistaken.

Further, while working with the newly-generated application, two steps are necessary when attempting to upload files:

1. Redis must be installed, running, and the following task must be run from the application root:
```
RUN_AT_EXIT_HOOKS=true TERM_CHILD=1 bundle exec resque-pool --daemon --environment development start
```
2. The FITS must be installed.

**Comment by jrgriffiniii** [comment]
After reimplementing the CurationConcerns-based Rails Models, I was able to successfully ingest the raster data set cea.tif from the following location:

http://download.osgeo.org/geotiff/samples/gdal_eg/

While this minimal functionality is available, there does appear to be a significant amount of work which must be undertaken in the structuring of the Views.  I shall work to focus upon these tasks next.
