### ISSUE TITLE
Generation of preview images

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#39]
Generate preview images from different formats.

**Comment by drh-stanford** [comment]
This is not easy for Shapefiles as far as I know.

**Comment by eliotjordan** [comment]
Looks like we could use [gdal_rasterize](http://www.gdal.org/gdal_rasterize.html) or shell out to something like [shp2img](http://mapserver.org/utilities/shp2img.html).

**Comment by drh-stanford** [comment]
I was successful generating a preview using these command invocations:

```
gdal_rasterize -burn 255 -tr 400 400 -l S_566_1914_lines -of GTiff S_566_1914_lines.shp preview.tif
gdal_translate -of PNG preview.tif preview.png

**Comment by drh-stanford** [comment]
- [ ] Assign FileSet pulldown to `file_set.original_file.has_mime_type` (PCDM::File)
- [ ] Document MIME types with parameters for Geo (see #63)
- [ ] Clone curation concerns' derivatives for our own `create_derivatives`
- [ ] Create Processors for the geo derivatives

**Comment by drh-stanford** [comment]
See https://github.com/projecthydra-labs/curation_concerns/issues/258
