### ISSUE TITLE
Reprojection of vector and raster data for display

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#40]
Reproject vector and raster data into WGS 84 for display.

**Comment by drh-stanford** [comment]
Going to wait on this one until #39 is finished so we can use its pattern on the derivative generation

**Comment by drh-stanford** [comment]
This may or may not require implementing `bf:cartographicProjection` -- although I think we'll be able to auto-detect and auto-populate that attribute.

**Comment by jayvarner** [comment]
We have been working really hard on making scanned maps display well online. Here is our process (that we have automated): https://github.com/emory-libraries-ecds/Code4Lib-2016-Workshop/blob/master/GDAL-Commands.md

**Comment by drh-stanford** [comment]
I'm surprised that you're seeing good results with `average` resampling. We're using `bilinear`. Do you have any specific comparisons -- are these scanned maps only?

**Comment by eliotjordan** [comment]
Clsoed by #103
