### ISSUE TITLE
Loading data into geoserver

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#41]
Create mechanism for loading data into a geoserver.

**Comment by eliotjordan** [comment]
Look at [Geoloader] (https://github.com/scholarslab/Geoloader).

**Comment by drh-stanford** [comment]
an example of `rgeoserver` is here: https://github.com/sul-dlss/gis-robot-suite/blob/master/robots/gisDelivery/load-geoserver.rb

**Comment by drh-stanford** [comment]
need to figure out how to do CI with geoserver. possibly with jetty or docker

**Comment by drh-stanford** [comment]
we discussed this and decided to do CI builds at the `rgeoserver` gem -- so mock up to the `rgeoserver` layer

**Comment by drh-stanford** [comment]
Pending #27

**Comment by drh-stanford** [comment]
Working on finding/building a vagrant VM for geoserver

**Comment by drh-stanford** [comment]
For local data access see https://github.com/projecthydra-labs/geo_concerns/blob/master/app/controllers/concerns/geo_concerns/download_behavior.rb#L15

**Comment by drh-stanford** [comment]
For uploading data to GeoServer rather than local files on a shared filesystem -- see http://docs.geoserver.org/stable/en/user/rest/api/datastores.html#workspaces-ws-datastores-ds-file-url-external-extension

**Comment by drh-stanford** [comment]
i have the structure in place to call the upload to GeoServer in a branch — https://github.com/projecthydra-labs/geo_concerns/compare/41-geoserver

specifically, it’ll go here — https://github.com/projecthydra-labs/geo_concerns/blob/6fe3c875d38093823bc0aa94910dd518913e1154/app/services/geo_concerns/delivery_service.rb#L11

one of my outstanding questions though is whether to fire the job from a generator that injects into the CharacterizeJob, or to keep it here — https://github.com/projecthydra-labs/geo_concerns/blob/6fe3c875d38093823bc0aa94910dd518913e1154/app/models/concerns/geo_concerns/file_set/derivatives.rb#L21-L24

**Comment by drh-stanford** [comment]
We still need to implement raster uploads.

I have a branch in `rgeoserver` to support raster uploads but it's untested as yet.

See https://github.com/sul-dlss/rgeoserver/tree/9-raster-upload
