### ISSUE TITLE
Identify useful geospatial ruby libraries

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#42]
Identify geospatial ruby libraries that might be useful for geo_concerns.

- [gdal-ruby] (https://github.com/zhm/gdal-ruby)
  - [Python API Documentation](https://pcjericks.github.io/py-gdalogr-cookbook/geometry.html) is helpful 
  - Too low level?
- [rgeo](https://github.com/rgeo/rgeo)
- [rgeoserver](https://github.com/sul-dlss/rgeoserver)

**Comment by drh-stanford** [comment]
`ffi-geos` are ruby bindings to the GEOS API

**Comment by eliotjordan** [comment]
[Geoloader] (https://github.com/scholarslab/Geoloader) for work with GeoServer.
