### ISSUE TITLE
Extend the RDF::Vocab Gem to support the OGC ontology in the RDF

### ISSUE THREAD

**Issue by jrgriffiniii** [projecthydra-labs/geo_concerns#65]
Like #64, this requires the extension of the [RDF::Vocab Gem](https://github.com/ruby-rdf/rdf-vocab).  However, this may raise conflicts with an existing implementation of the RDF::Vocab::OGC Module (for the [Open Graph protocol](https://github.com/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/ogc.rb)).  In cases where this conflict cannot be resolved, it may be necessary to support the ontology within another GitHub project.

**Comment by drh-stanford** [comment]
Can we close this now that we're using `dc:coverage`?

**Comment by jrgriffiniii** [comment]
As indicated by @drh-stanford, the resolution for #83 deprecates this issue.
