### ISSUE TITLE
Define attribute requirements

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#69]
What are the minimum attributes that are needed to satisfy the Geoblacklight schema requirements.

**Comment by eliotjordan** [comment]
Notes to start with: https://docs.google.com/document/d/10Vy70CX7vIYD03fRM8gogU1PbBH-KgnXxFyDjfUCDAA/edit#

**Comment by drh-stanford** [comment]
We want to look at GeoJSON-LD as a possible solution for bounding box, projections, etc.

**Comment by johnhuck** [comment]
https://github.com/geoblacklight/geoblacklight-schema/blob/master/docs/geoblacklight-schema.markdown

**Comment by johnhuck** [comment]
Our working document: https://docs.google.com/spreadsheets/d/1QgnrLijeUOV-tFsyRE7fZpY4n_5D-8PJO3o8VxORPiw/edit?usp=sharing

**Comment by johnhuck** [comment]
Links to the Curation Concerns basic and required metadata gems
https://github.com/projecthydra-labs/curation_concerns/blob/88af416bd2fb1088827a090f2ecf98cbb61a2ca5/curation_concerns-models/app/models/concerns/curation_concerns/basic_metadata.rb

https://github.com/projecthydra-labs/curation_concerns/blob/88af416bd2fb1088827a090f2ecf98cbb61a2ca5/curation_concerns-models/app/models/concerns/curation_concerns/required_metadata.rb

**Comment by drh-stanford** [comment]
I'm going to close this one and create another for the outstanding issue of the multivalued attributes.
