### ISSUE TITLE
Update CurationConcerns gem

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#72]
Update to newest version CurationConcerns.

**Comment by jrgriffiniii** [comment]
@eliotjordan this appears to be currently blocking me from implementing the RSpec test suites for #70.  Would you object to me attempting to resolve this before moving forward?  (My fear is that, should I attempt to resolve #70 in isolation, there may be conflicts introduced in my attempts to get the RSpec tests functioning with CurationConcerns v. 0.10.x).

If so, then I can work to resolve other issues for the sprint until this has been completed.  Please let me know how best to proceed.

**Comment by eliotjordan** [comment]
@jrgriffiniii Did you make any headway on this? I was about to give it a shot, but I don't want to duplicate our efforts here.

**Comment by jrgriffiniii** [comment]
@eliotjordan My apologies, I haven't had the opportunity to return to this throughout this morning.  I anticipate that I shouldn't be in the position to progress significantly with this (or #70) until this evening.

**Comment by eliotjordan** [comment]
Gotcha. I'll keep plugging away on this one then.
